mftutor/gallery/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView, DeleteView
from ..tutor.auth import tutorbest_required
from .views import NewGalleryView, UploadPictureView, PublishPicturesView, PublishView, PictureView, DeletePictureView, GalleryListView
from .models import Picture, Gallery

urlpatterns = patterns('',
    url('new', NewGalleryView.as_view(), name='new_gallery'),
    url('upload', UploadPictureView.as_view(), name='upload_picture'),
    url(r'^publish/(?P<pk>\d+)/$', PublishPicturesView.as_view(), name='publish_picture'),
    url('publishgallery', PublishView.as_view(), name='publish_gallery'),
    url(r'^(?P<id>\d+)/$', PictureView.as_view(), name='picture_gallery'),
    url(r'^$', GalleryListView.as_view(), name='list_galleries'),
    url(r'^delete/(?P<pk>\d+)/$',
        DeletePictureView.as_view(),
        name='delete_picture'),
)

mftutor/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'mftutor.views.home', name='home'),
    # url(r'^mftutor/', include('mftutor.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('mftutor.news.urls')),
    url(r'^', include('mftutor.page.urls')),
    url(r'^', include('mftutor.tutor.urls')),
    url(r'^events/', include('mftutor.events.urls')),
    url(r'^email/', include('mftutor.tutormail.urls')),
    url(r'^shirt/', include('mftutor.shirt.urls')),
    url(r'^document/', include('mftutor.documents.urls')),
    url(r'^confirmation/', include('mftutor.confirmation.urls')),
    url(r'^rus/', include('mftutor.rus.urls')),
    url(r'^reg/', include('mftutor.reg.urls')),
    url(r'^burtavle/frame/$', 'mftutor.reg.views.burtavle', name="burtavle"),
    url(r'^burtavle/$', 'mftutor.reg.views.burtavle_frameset', name="burtavle_frameset"),
    url(r'^dump/', include('mftutor.dump.urls')),
    url(r'^browser/', include('mftutor.browser.urls')),
    url(r'^tutorhold/', include('mftutor.rusclass.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mftutor/gallery/models.py
# coding: utf-8
from datetime import datetime
from django.db import models
from .. import settings

class Picture(models.Model):
    time_of_upload = models.DateTimeField(editable = False, auto_now_add = True)
    gallery = models.ForeignKey('Gallery', verbose_name = "Galleri")
    is_published = models.BooleanField(editable = True, verbose_name = "Publish", default = False)

    def pic_upload_to(instance, filename):
        return "gallery/" + str(instance.gallery.pk) + "/" + filename
    pic_file = models.ImageField(upload_to = pic_upload_to, verbose_name="Billede")
    def get_absolute_url(self):
        return settings.MEDIA_URL + unicode(self.pic_file)
    
class Gallery(models.Model):
    title = models.CharField(max_length = 100, verbose_name = "Titel")
    time_of_creation = models.DateTimeField(editable = False, auto_now_add = True)
    def __unicode__(self):
        return '[Galleri '+self.title+']'
    
    

mftutor/tutor/models.py
# coding: utf-8
# See https://docs.djangoproject.com/en/1.4/topics/auth/
# for a discussion on user profiles and django.contrib.auth
from __future__ import unicode_literals

import re

from django.utils.encoding import python_2_unicode_compatible
from django.db import models, IntegrityError
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from mftutor import settings
from mftutor.tutor.managers import TutorProfileManager, TutorManager, \
    VisibleTutorGroups, RusManager, RusClassManager
from mftutor.tutor import tutorpicture_upload_to


# User data for the project that does not vary from year to year
@python_2_unicode_compatible
class TutorProfile(models.Model):
    objects = TutorProfileManager()

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)

    name = models.CharField(
        max_length=60, verbose_name="Fulde navn")
    street = models.CharField(
        max_length=80, blank=True, verbose_name="Adresse")
    city = models.CharField(
        max_length=40, blank=True, verbose_name="Postnr. og by")
    phone = models.CharField(
        max_length=20, blank=True, verbose_name="Telefonnr.")
    email = models.EmailField(
        max_length=75, verbose_name="E-mailadresse")

    study = models.CharField(
        max_length=60, blank=True, verbose_name="Studieretning")
    studentnumber = models.CharField(
        max_length=20, unique=True, blank=True, null=True,
        verbose_name="Årskortnummer")

    picture = models.ImageField(
        upload_to=tutorpicture_upload_to,
        blank=True,
    )

    def __str__(self):
        try:
            u = self.user
        except User.DoesNotExist:
            u = None
        return '%s %s %s' % (
            self.studentnumber,
            self.get_full_name(),
            u.username if u else '(no user)',
        )

    def set_default_email(self):
        if self.email == '':
            if re.match(r'[A-Z]{2}[0-9]{5}$', self.studentnumber):
                domain = settings.DEFAULT_ASB_EMAIL_DOMAIN
            else:
                domain = settings.DEFAULT_EMAIL_DOMAIN
            self.email = '%s@%s' % (self.studentnumber, domain)

    class Meta:
        verbose_name = 'tutorprofil'
        verbose_name_plural = verbose_name + 'er'

    def get_full_name(self):
        return self.name

    def get_or_create_user(self):
        u = self.user
        if u is not None:
            return u
        sn = self.studentnumber
        if sn is None:
            raise IntegrityError(
                'TutorProfile.get_or_create_user: No studentnumber')
        u = User(
            username=self.studentnumber,
            email=self.email)
        self.set_user_name(u)
        u.save()
        self.user = u
        self.save()

    @classmethod
    def set_instance_user_name(cls, tp, user=None):
        if user is None:
            user = tp.user
            if user is None:
                raise ValueError(
                    "set_instance_user_name: TutorProfile has no user")
        try:
            first_name, last_name = tp.name.split(' ', 1)
        except ValueError:
            first_name, last_name = tp.name, ''
        user.first_name = first_name
        user.last_name = last_name

    def set_user_name(self, user=None):
        self.set_instance_user_name(self, user)

    def clean(self):
        pattern = r'\+?[0-9 ]+$'
        if not re.match(pattern, self.phone):
            raise ValidationError('Telefonnummer må kun indeholde tal')
        self.phone = self.phone.replace(' ', '')


# "Arbejdsgruppe"
@python_2_unicode_compatible
class TutorGroup(models.Model):
    objects = models.Manager()
    visible_groups = VisibleTutorGroups()

    handle = models.CharField(
        max_length=20, verbose_name="Kort navn",
        help_text="Bruges i gruppens emailadresse")
    name = models.CharField(
        max_length=40, verbose_name="Langt navn",
        help_text="Vises på hjemmesiden")
    visible = models.BooleanField(default=False)
    year = models.IntegerField(verbose_name="Tutorår", null=True)
    leader = models.ForeignKey('Tutor', verbose_name='Gruppeansvarlig', null=True)

    def __str__(self):
        return '%s %s' % (self.handle, self.year)

    class Meta:
        ordering = ['-year', 'name', 'handle']
        verbose_name = 'arbejdsgruppe'
        verbose_name_plural = verbose_name + 'r'


# "Rushold"
@python_2_unicode_compatible
class RusClass(models.Model):
    objects = RusClassManager()

    id = models.AutoField(primary_key=True)
    official_name = models.CharField(
        max_length=20, verbose_name="AU-navn",
        help_text=u"DA1, MØ3, osv.")
    internal_name = models.CharField(
        max_length=20, verbose_name="Internt navn",
        help_text=u"Dat1, Møk3, osv.")
    handle = models.CharField(
        max_length=20, verbose_name="Email",
        help_text=u"dat1, mok3, osv. Bruges i holdets emailadresse")
    year = models.IntegerField(verbose_name="Tutorår")

    def get_study(self):
        for official_name, handle, internal_name in settings.RUSCLASS_BASE:
            if self.handle.startswith(handle):
                return internal_name

    def get_tutors(self):
        return Tutor.objects.filter(rusclass=self)

    def get_russes(self):
        return Rus.objects.filter(rusclass=self)

    def __str__(self):
        return self.internal_name

    class Meta:
        verbose_name = 'rushold'
        verbose_name_plural = verbose_name

        ordering = ['year', 'internal_name']


# Membership of a user for a single year
@python_2_unicode_compatible
class Tutor(models.Model):
    objects = TutorManager()

    id = models.AutoField(primary_key=True)
    profile = models.ForeignKey(TutorProfile)
    year = models.IntegerField(verbose_name="Tutorår")
    groups = models.ManyToManyField(
        TutorGroup, verbose_name="Arbejdsgrupper", blank=True)
    early_termination = models.DateTimeField(
        null=True, blank=True, verbose_name="Ekskluderet",
        help_text="Tidspunkt i året hvor tutoren stopper i foreningen")
    early_termination_reason = models.TextField(
        null=True, blank=True, verbose_name="Eksklusionsårsag",
        help_text="Årsag til at tutoren stopper")
    rusclass = models.ForeignKey(RusClass, null=True, blank=True)

    @classmethod
    def members(cls, year=None):
        if year is None:
            year = settings.YEAR

        return cls.objects.filter(
            year=year,
            early_termination__isnull=True)

    @classmethod
    def group_members(cls, handle, year=None):
        if isinstance(handle, TutorGroup):
            return cls.members(handle.year).filter(groups=handle)
        else:
            return cls.members(year).filter(groups__handle__exact=handle)

    def has_rusclass(self, year=None):
        if year is None:
            year = settings.YEAR

        return self.is_tutorbur() or self.rusclass

    def is_member(self, year=None):
        if year is None:
            year = settings.YEAR

        if self.year != year:
            return False
        elif self.early_termination is not None:
            return False
        else:
            return True
    is_member.boolean = True

    def is_tutorbest(self, year=None):
        if not self.is_member(year=year):
            return False
        elif self.groups.filter(handle__exact='best').exists():
            return True
        else:
            return False
    is_tutorbest.boolean = True

    def is_tutorbur(self):
        if not self.is_member():
            return False
        elif self.is_tutorbest():
            return True
        elif self.groups.filter(handle__exact='buret').exists():
            return True
        else:
            return False
    is_tutorbur.boolean = True

    def can_manage_rusclass(self, rusclass):
        return (self.is_tutorbest() or
                self.is_tutorbur() or
                self.rusclass == rusclass)

    def __str__(self):
        try:
            p = self.profile
        except:
            p = None
        return '%s (%s)' % (p, self.year)

    class Meta:
        ordering = ['-year']
        verbose_name = 'tutor'
        verbose_name_plural = verbose_name + 'er'
        unique_together = (('profile', 'year'),)


class TutorInTutorGroup(models.Model):
    tutorgroup = models.ForeignKey(TutorGroup, to_field='id')
    tutor = models.ForeignKey(Tutor)


@python_2_unicode_compatible
class BoardMember(models.Model):
    id = models.AutoField(primary_key=True)
    tutor = models.ForeignKey(Tutor)
    position = models.IntegerField(verbose_name="Rækkefølge")
    title = models.CharField(max_length=50, verbose_name="Titel")

    def __str__(self):
        return "%s %s" % (self.title, self.tutor)

    class Meta:
        ordering = ['tutor__year', 'position']
        verbose_name = 'bestyrelsesmedlem'
        verbose_name_plural = verbose_name + 'mer'


# Freshman semester of a user for a single year
class Rus(models.Model):
    objects = RusManager()

    id = models.AutoField(primary_key=True)
    profile = models.ForeignKey(TutorProfile)
    year = models.IntegerField(verbose_name="Tutorår")
    rusclass = models.ForeignKey(RusClass, null=True)

    arrived = models.BooleanField(verbose_name="Ankommet", default=False)
    initial_rusclass = models.ForeignKey(
        RusClass, null=True, related_name='initial_rus_set')

    class Meta:
        verbose_name = 'rus'
        verbose_name_plural = verbose_name + 'ser'

        ordering = ['rusclass', 'profile']

    def json_of(self):
        if self.initial_rusclass:
            initial_handle = self.initial_rusclass.handle
        else:
            initial_handle = None
        return {
            'year': self.year,
            'rusclass': self.rusclass.handle,
            'arrived': self.arrived,
            'pk': self.profile.pk,

mftutor/gallery/views.py
# coding: utf-8
from django import forms
from django.shortcuts import get_object_or_404
from django.forms.extras import SelectDateWidget
from django.views.generic import UpdateView, TemplateView, CreateView, DeleteView
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import Picture, Gallery
from ..tutor.auth import tutorbest_required



class UploadPictureForm(forms.ModelForm):
    class Meta:
        model = Picture


class NewGalleryView(CreateView):
    model = Gallery
    template_name = "creategallery.html"

    def get_success_url(self):
        return reverse("list_galleries")

    @method_decorator(tutorbest_required)
    def dispatch(self, *args, **kwargs):
        return super(NewGalleryView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        d = super(NewGalleryView, self).get_context_data(**kwargs)
        d['create'] = True
        return d


class UploadPictureView(CreateView):
    model = Picture
    template_name = "pictureuploader.html"
    form_class = UploadPictureForm

    def get_success_url(self):
        return reverse("list_galleries")

    @method_decorator(tutorbest_required)
    def dispatch(self, *args, **kwargs):
        return super(UploadPictureView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        d = super(UploadPictureView, self).get_context_data(**kwargs)
        d['create'] = True
        return d

class PublishPicturesView(UpdateView):
    model = Picture
    template_name = "publishpictures.html"
    form_class = UploadPictureForm

    def get_success_url(self):
        return reverse("list_"+self.object.type)
    @method_decorator(tutorbest_required)
    def dispatch(self, *args, **kwargs):
        return super(UploadPictureView,self).dispatch(*args,**kwargs)
    def get_context_data(self, **kwargs):
        d = super(UploadPictureView, self).get_context_data(**kwargs)
        d['create'] = False
        return d

class DeletePictureView(DeleteView):
    model = Picture

    def get_success_url(self):
        return reverse("list_"+self.object.type)

    @method_decorator(tutorbest_required)
    def dispatch(self, *args, **kwargs):
        return super(DeletePictureView, self).dispatch(*args, **kwargs)

class PublishView(TemplateView):
    def get_queryset(self):
        return Picture.objects.filter(is_published__exact = True)
    def get(self, request):
        pictures = self.get_queryset()
        params = {
                 "pictures":pictures,
        }        
        return self.render_to_response(params)

    @method_decorator(tutorbest_required)
    def dispatch(self, *args, **kwargs):
        return super(PublishView, self).dispatch(*args, **kwargs)

    def get_template_names(self):
        return ('gallery.html',)

class PictureView(TemplateView):
    def get_queryset(self):
        return Picture.objects.filter(is_published__exact = True)

    def get(self, request, id=None):
        gallery = get_object_or_404(Gallery.objects.filter(pk=id))
        
        pictures = Picture.objects.filter(gallery__exact=gallery)
        params = {
                 "gallery":gallery,
                 "pictures":pictures,
        }        
        return self.render_to_response(params)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(PictureView, self).dispatch(*args, **kwargs)

    def get_template_names(self):
        return ('galleryview.html',)

class GalleryListView(TemplateView):
    def get_queryset(self):
        return Gallery.objects.all()

    def get(self, request):
        gallery_list = self.get_queryset()
        params = {
                 "gallery_list":gallery_list
        }        
        return self.render_to_response(params)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(GalleryListView, self).dispatch(*args, **kwargs)

    def get_template_names(self):
        return ("galleries.html",)

mftutor/rus/templates/rus/base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block header %}
<div id="rusheader" style="position: relative"><a href="/"><img src="{% static "matfyslogo2015.jpg" %}" /></a>
</div>
{% endblock %}
{% block menu %}
<li class="trigger">
<a href="{% url 'rus_start' %}">Start</a>
<ul class="subnav">
  <li><a href="{% url 'rus_kontakt' %}">Kontakt</a></li>
  {#<li><a href="{% url 'rus_nyheder' %}">Nyheder</a></li>#}
  {#<li><a href="{% url 'rus_rse' %}">Dansk som andetsprog</a></li>#}
  {% if rus %}
  <li><a href="{% url 'rus_password_change' %}">Skift kodeord</a></li>
  {% endif %}
</ul>
</li>
<li class="trigger">
<a href="{% url 'rus_program' %}">Program</a>
<ul class="subnav">
  <li><a href="{% url 'rus_kalender' %}">Kalender</a></li>
</ul>
</li>
<li class="trigger">
<a href="{% url 'rus_rusbrev' %}">Rusbrev</a>
</li>
<li class="trigger">
<a href="{% url 'rus_holdlister' %}">Holdlister</a>
{% if rus %}
<ul class="subnav">
  <li><a href="{% url 'rus_profil' %}">Mine oplysninger</a></li>
</ul>
{% endif %}
</li>
<li class="trigger">
<a href="{% url 'rus_gallery' %}">Billeder</a>
</li>
{% endblock %}

mftutor/rus/templates/rus/gallery.html
{% extends "rus/base.html" %}
{% load staticfiles %}
{% block title %}Galleri{% endblock %}

{% block content %}
<h1>Galleri</h1>

<p>Når du besøger galleriet, bliver du bedt om et brugernavn og kodeord. Hertil
skal du benytte dit brugernavn og kodeord til rushjemmesiden.
Man skal være logget ind for at se billeder fra galleriet.</p>

<p>Besøg <a href="{% static "rusgallery/" %}">galleriet</a>.</p>

{% endblock %}

mftutor/rus/templates/rus/start.html
{% extends "rus/base.html" %}
{% load staticfiles %}
{% block title %}Start{% endblock %}

{% block content %}

{% if rus %}
<h1>{{ rusclass }}</h1>

{% if my_info_form %}
{% if params.form_saved %}
<p>Dine kontaktoplysninger er gemt.</p>
{% elif params.form_errors %}
{% else %}
<p>Du mangler at udfylde dine kontaktoplysninger!</p>
{% endif %}
{{ my_info_form.non_field_errors }}
<form class="twocol" method="post">{% csrf_token %}
    <div class="label"><label for="id_phone">Telefonnummer:</label></div>
    <div class="field">{{ my_info_form.phone }}</label> {{ my_info_form.phone.errors }}</div>
    <div class="label"><label for="id_email">Email:</label></div>
    <div class="field">{{ my_info_form.email }}</label> {{ my_info_form.email.errors }}</div>
    <div class="field"><input type="submit" value="Gem" /></div>
</form>
{% endif %}

<table class="person_list" cellspacing="0">
<col span="3" />
<tr class="heading"><td colspan="3"><h3>Tutorer</h3></td></tr>

<tr>
    <th>Navn</th>
    <th>Mobil</th>
    <th>Email</th>
</tr>
{% for tutor in rusclass_tutors %}
    <tr>
        <td>{{ tutor.profile.get_full_name }}</td>
        <td class="phone"><a href="tel:{{ tutor.profile.phone }}">{{ tutor.profile.phone }}</a></td>
        <td><a href="mailto:{{ tutor.profile.email }}">{{ tutor.profile.email }}</a></td>
    </tr>
{% endfor %}

<tr class="heading"><td colspan="3"><h3>Russer</h3></td></tr>

<tr>
    <th>Navn</th>
    <th>Mobil</th>
    <th>Email</th>
</tr>
{% for rus in rusclass_russes %}
    <tr>
        <td>{{ rus.profile.get_full_name }}</td>
        <td class="phone"><a href="tel:{{ rus.profile.phone }}">{{ rus.profile.phone }}</a></td>
        <td><a href="mailto:{{ rus.profile.email }}">{{ rus.profile.email }}</a></td>
    </tr>
{% endfor %}
</table>

<div style="height: 1em"></div>

{% endif %}

<h1>Information til kommende russer</h1>

<p>
Hvad og hvornår er rusdagene?
Hvornår modtager du dit rusbrev?
Er du helt fortabt?
Så er du kommet til det rette sted, hvis du skal starte på et af følgende studier:
</p>

<ul>
    <li><a href="http://studerende.au.dk/studier/fagportaler/matematik/studiestart/">
        Matematik og matematik/økonomi</a></li>
    <li><a href="http://studerende.au.dk/studier/fagportaler/fysik/studiestart/">
        Fysik</a></li>
    <li><a href="http://studerende.au.dk/studier/fagportaler/nanoscience/studiestart/">
        Nanoscience</a></li>
    <li><a href="http://studerende.au.dk/studier/fagportaler/datalogi/studiestart/">
        Datalogi og it</a></li>
</ul>

<h2>Om rusdagene</h2>

<p>Rusdagene (eller introduktionsdagene) er tre dage, der afholdes inden
studiestart. Formålet med dagene er at give dig og dit hold en god start på
studiet. I rusdagene vil dine tutorer sørge for, at holdet bliver rystet samme,
at I får købt bøger, og der vil også være oplæg om arbejdsformer og læsegrupper.
Rusdagene er ikke obligatoriske, men vi vil på det stærkeste anbefale, at du
deltager. Hvis du er forhindret (eller ikke ønsker at deltage) vil vi meget
gerne <a href="{% url 'rus_kontakt' %}">have besked om det</a>.</p>

<h2>Hjælpen er nær</h2>

<p>
På denne hjemmeside kan du blandt andet finde en <a href="{% url 'rus_kalender' %}">kalender</a>
med de vigtigste datoer for studiestarten
(f.eks. hvorn&aring;r du skal starte og hvorn&aring;r du skal p&aring; rustur),
en onlineudgave af <a href="{% url 'rus_rusbrev' %}">rusbrevet</a>
og ikke mindst <a href="{% url 'rus_program' %}">studiestartsprogrammet</a>,
s&aring; du kan se, hvad du skal lave de f&oslash;rste dage p&aring; universitetet.
</p>

<p>
Hvis du har sp&oslash;rgm&aring;l eller kommentarer skal du v&aelig;re mere end velkommen til at kontakte os.
Se hvordan under <a href="{% url 'rus_kontakt' %}">Kontakt os</a>.
</p>

<p>
Vi gl&aelig;der os til at se dig!
</p>

{# 2015-08-03 hidden: #}
<!--
<h2>Vil du fortælle om din studiestart?</h2>

<p>
Vi er, ligesom I, meget spændte på den kommende studiestart her på Aarhus
Universitet. Science and Technology søger i den forbindelse nogle studerende,
der vil hjælpe os med at dække studiestarten på sociale medier eller deltage i
et par interviews. Hvis du har lyst til at være med, så skriv til Frederik på
<a href="mailto:frros@science.au.dk">frros@science.au.dk</a>.
</p>
-->

<h2>Vejviser</h2>

<p><iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=ny+munkegade+118,+8000+%C3%A5rhus,+denmark&amp;aq=&amp;sll=56.16617,10.199861&amp;sspn=0.009271,0.033023&amp;g=ny+munkegade+116,+8000+%C3%A5rhus,+denmark&amp;ie=UTF8&amp;hq=&amp;hnear=Ny+Munkegade+118,+8000+Aarhus,+Aarhus+C,+Denmark&amp;ll=56.166164,10.199862&amp;spn=0.001159,0.004128&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=ny+munkegade+118,+8000+%C3%A5rhus,+denmark&amp;aq=&amp;sll=56.16617,10.199861&amp;sspn=0.009271,0.033023&amp;g=ny+munkegade+116,+8000+%C3%A5rhus,+denmark&amp;ie=UTF8&amp;hq=&amp;hnear=Ny+Munkegade+118,+8000+Aarhus,+Aarhus+C,+Denmark&amp;ll=56.166164,10.199862&amp;spn=0.001159,0.004128&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Vis st&oslash;rre kort</a></small></p>
</p>

{% endblock %}
{% block bottom %}
<div style="margin-top: 1em; text-align: center">
<a href="{% static "matfys2015.jpg" %}">
<img src="{% static "matfys2015-800px.jpg" %}" style="width: 800px; height: 533px" />
</a>
</div>
{% endblock %}