mftutor/browser/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import ProfileView, RusClassView, GroupView, SearchView

urlpatterns = patterns('',
    url(r'^search/$', login_required(SearchView.as_view()),
        name='browser_search'),
    url(r'^profile/(?P<studentnumber>[0-9a-zA-Z]+)/$', login_required(ProfileView.as_view()),
        name='browser_profile'),
    url(r'^rusclass/(?P<year>\d+)/(?P<handle>[a-z0-9]+)/$', login_required(RusClassView.as_view()),
        name='browser_rusclass'),
    url(r'^group/(?P<year>\d+)/(?P<handle>[a-z0-9]+)/$', login_required(GroupView.as_view()),
        name='browser_group'),
    )

mftutor/page/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

static_pages = [url('^'+x+'/', TemplateView.as_view(template_name=x+'.html'), name=x) for x in (
        'vedtaegter',
        'gruppekatalog',
        'rus2tur',
        'sponsor',
        'kontakt',
        'todo',
        'intro',
        'feeds',
        )]
urlpatterns = patterns('',
    *static_pages)

mftutor/tutor/urls.py
from django.conf.urls import patterns, url
from ..aliases.views import AliasesView, MyGroupsView
from .views import (
    logout_view, login_view, profile_view, tutor_password_change_view,
    UploadPictureView, tutors_view, TutorAdminView, switch_user, FrontView,
    BoardAdminView, GroupLeaderView, ResetPasswordView, BoardMemberListView,
    TutorDumpView, ChangeYearView)
from .auth import tutorbest_required, tutor_required

urlpatterns = patterns('',
    url(r'^$', FrontView.as_view(), name='front'),
    url(r'^tutors/$', tutor_required(tutors_view), name='tutors'),
    url(r'^tutors/(?P<group>[^/?]+)/$', tutor_required(tutors_view), name='tutorgroup'),
    url(r'^tutordump/$', tutor_required(TutorDumpView.as_view()), name='tutordump'),
    url(r'^tutordump/(?P<group>[^/?]+)/$', tutor_required(TutorDumpView.as_view()), name='tutordumpgroup'),
    url(r'^board/$', BoardMemberListView.as_view(), name='board'),
    url(r'^logout/$', logout_view, name="logout_view"),
    url(r'^login/$', login_view, name='tutor_login'),
    url(r'^login/\?err=(?P<err>.*)$', login_view, name='login_error'),
    url(r'^profile/$', tutor_required(profile_view), name='profile_view'),
    url(r'^profile/password/$', tutor_required(tutor_password_change_view), name='password_change'),
    url(r'^groups/$', tutor_required(AliasesView.as_view()), name='aliases'),
    url(r'^groups/me/$', tutor_required(MyGroupsView.as_view()), name='groups_view'),
    url(r'^profile/picture/$', tutor_required(UploadPictureView.as_view()), name='upload_picture_view'),
    url(r'^tutoradmin/$', tutorbest_required(TutorAdminView.as_view()), name='tutor_admin'),
    url(r'^gruppeansvarlige/$', tutorbest_required(GroupLeaderView.as_view()), name='groupleader_admin'),
    url(r'^resetpassword/$', tutorbest_required(ResetPasswordView.as_view()), name='reset_password'),
    url(r'^boardadmin/(?P<year>\d+)/$', tutorbest_required(BoardAdminView.as_view()), name='board_admin'),
    url(r'^su/(?P<new_user>[^/]*)/$', switch_user),
    url(r'^(?P<year>20[0-9]{2})/(?P<remainder>.*)$', ChangeYearView.as_view(), name='change_year'),
)

mftutor/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'mftutor.views.home', name='home'),
    # url(r'^mftutor/', include('mftutor.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('mftutor.news.urls')),
    url(r'^', include('mftutor.page.urls')),
    url(r'^', include('mftutor.tutor.urls')),
    url(r'^events/', include('mftutor.events.urls')),
    url(r'^email/', include('mftutor.tutormail.urls')),
    url(r'^shirt/', include('mftutor.shirt.urls')),
    url(r'^document/', include('mftutor.documents.urls')),
    url(r'^confirmation/', include('mftutor.confirmation.urls')),
    url(r'^rus/', include('mftutor.rus.urls')),
    url(r'^reg/', include('mftutor.reg.urls')),
    url(r'^burtavle/frame/$', 'mftutor.reg.views.burtavle', name="burtavle"),
    url(r'^burtavle/$', 'mftutor.reg.views.burtavle_frameset', name="burtavle_frameset"),
    url(r'^dump/', include('mftutor.dump.urls')),
    url(r'^browser/', include('mftutor.browser.urls')),
    url(r'^tutorhold/', include('mftutor.rusclass.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mftutor/browser/models.py
from django.db import models

# Create your models here.

mftutor/tutor/models.py
# coding: utf-8
# See https://docs.djangoproject.com/en/1.4/topics/auth/
# for a discussion on user profiles and django.contrib.auth
from __future__ import unicode_literals

import re

from django.utils.encoding import python_2_unicode_compatible
from django.db import models, IntegrityError
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from mftutor import settings
from mftutor.tutor.managers import TutorProfileManager, TutorManager, \
    VisibleTutorGroups, RusManager, RusClassManager
from mftutor.tutor import tutorpicture_upload_to


# User data for the project that does not vary from year to year
@python_2_unicode_compatible
class TutorProfile(models.Model):
    objects = TutorProfileManager()

    id = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)

    name = models.CharField(
        max_length=60, verbose_name="Fulde navn")
    street = models.CharField(
        max_length=80, blank=True, verbose_name="Adresse")
    city = models.CharField(
        max_length=40, blank=True, verbose_name="Postnr. og by")
    phone = models.CharField(
        max_length=20, blank=True, verbose_name="Telefonnr.")
    email = models.EmailField(
        max_length=75, verbose_name="E-mailadresse")

    study = models.CharField(
        max_length=60, blank=True, verbose_name="Studieretning")
    studentnumber = models.CharField(
        max_length=20, unique=True, blank=True, null=True,
        verbose_name="Årskortnummer")

    picture = models.ImageField(
        upload_to=tutorpicture_upload_to,
        blank=True,
    )

    def __str__(self):
        try:
            u = self.user
        except User.DoesNotExist:
            u = None
        return '%s %s %s' % (
            self.studentnumber,
            self.get_full_name(),
            u.username if u else '(no user)',
        )

    def set_default_email(self):
        if self.email == '':
            if re.match(r'[A-Z]{2}[0-9]{5}$', self.studentnumber):
                domain = settings.DEFAULT_ASB_EMAIL_DOMAIN
            else:
                domain = settings.DEFAULT_EMAIL_DOMAIN
            self.email = '%s@%s' % (self.studentnumber, domain)

    class Meta:
        verbose_name = 'tutorprofil'
        verbose_name_plural = verbose_name + 'er'

    def get_full_name(self):
        return self.name

    def get_or_create_user(self):
        u = self.user
        if u is not None:
            return u
        sn = self.studentnumber
        if sn is None:
            raise IntegrityError(
                'TutorProfile.get_or_create_user: No studentnumber')
        u = User(
            username=self.studentnumber,
            email=self.email)
        self.set_user_name(u)
        u.save()
        self.user = u
        self.save()

    @classmethod
    def set_instance_user_name(cls, tp, user=None):
        if user is None:
            user = tp.user
            if user is None:
                raise ValueError(
                    "set_instance_user_name: TutorProfile has no user")
        try:
            first_name, last_name = tp.name.split(' ', 1)
        except ValueError:
            first_name, last_name = tp.name, ''
        user.first_name = first_name
        user.last_name = last_name

    def set_user_name(self, user=None):
        self.set_instance_user_name(self, user)

    def clean(self):
        pattern = r'\+?[0-9 ]+$'
        if not re.match(pattern, self.phone):
            raise ValidationError('Telefonnummer må kun indeholde tal')
        self.phone = self.phone.replace(' ', '')


# "Arbejdsgruppe"
@python_2_unicode_compatible
class TutorGroup(models.Model):
    objects = models.Manager()
    visible_groups = VisibleTutorGroups()

    handle = models.CharField(
        max_length=20, verbose_name="Kort navn",
        help_text="Bruges i gruppens emailadresse")
    name = models.CharField(
        max_length=40, verbose_name="Langt navn",
        help_text="Vises på hjemmesiden")
    visible = models.BooleanField(default=False)
    year = models.IntegerField(verbose_name="Tutorår", null=True)
    leader = models.ForeignKey('Tutor', verbose_name='Gruppeansvarlig', null=True)

    def __str__(self):
        return '%s %s' % (self.handle, self.year)

    class Meta:
        ordering = ['-year', 'name', 'handle']
        verbose_name = 'arbejdsgruppe'
        verbose_name_plural = verbose_name + 'r'


# "Rushold"
@python_2_unicode_compatible
class RusClass(models.Model):
    objects = RusClassManager()

    id = models.AutoField(primary_key=True)
    official_name = models.CharField(
        max_length=20, verbose_name="AU-navn",
        help_text=u"DA1, MØ3, osv.")
    internal_name = models.CharField(
        max_length=20, verbose_name="Internt navn",
        help_text=u"Dat1, Møk3, osv.")
    handle = models.CharField(
        max_length=20, verbose_name="Email",
        help_text=u"dat1, mok3, osv. Bruges i holdets emailadresse")
    year = models.IntegerField(verbose_name="Tutorår")

    def get_study(self):
        for official_name, handle, internal_name in settings.RUSCLASS_BASE:
            if self.handle.startswith(handle):
                return internal_name

    def get_tutors(self):
        return Tutor.objects.filter(rusclass=self)

    def get_russes(self):
        return Rus.objects.filter(rusclass=self)

    def __str__(self):
        return self.internal_name

    class Meta:
        verbose_name = 'rushold'
        verbose_name_plural = verbose_name

        ordering = ['year', 'internal_name']


# Membership of a user for a single year
@python_2_unicode_compatible
class Tutor(models.Model):
    objects = TutorManager()

    id = models.AutoField(primary_key=True)
    profile = models.ForeignKey(TutorProfile)
    year = models.IntegerField(verbose_name="Tutorår")
    groups = models.ManyToManyField(
        TutorGroup, verbose_name="Arbejdsgrupper", blank=True)
    early_termination = models.DateTimeField(
        null=True, blank=True, verbose_name="Ekskluderet",
        help_text="Tidspunkt i året hvor tutoren stopper i foreningen")
    early_termination_reason = models.TextField(
        null=True, blank=True, verbose_name="Eksklusionsårsag",
        help_text="Årsag til at tutoren stopper")
    rusclass = models.ForeignKey(RusClass, null=True, blank=True)

    @classmethod
    def members(cls, year=None):
        if year is None:
            year = settings.YEAR

        return cls.objects.filter(
            year=year,
            early_termination__isnull=True)

    @classmethod
    def group_members(cls, handle, year=None):
        if isinstance(handle, TutorGroup):
            return cls.members(handle.year).filter(groups=handle)
        else:
            return cls.members(year).filter(groups__handle__exact=handle)

    def has_rusclass(self, year=None):
        if year is None:
            year = settings.YEAR

        return self.is_tutorbur() or self.rusclass

    def is_member(self, year=None):
        if year is None:
            year = settings.YEAR

        if self.year != year:
            return False
        elif self.early_termination is not None:
            return False
        else:
            return True
    is_member.boolean = True

    def is_tutorbest(self, year=None):
        if not self.is_member(year=year):
            return False
        elif self.groups.filter(handle__exact='best').exists():
            return True
        else:
            return False
    is_tutorbest.boolean = True

    def is_tutorbur(self):
        if not self.is_member():
            return False
        elif self.is_tutorbest():
            return True
        elif self.groups.filter(handle__exact='buret').exists():
            return True
        else:
            return False
    is_tutorbur.boolean = True

    def can_manage_rusclass(self, rusclass):
        return (self.is_tutorbest() or
                self.is_tutorbur() or
                self.rusclass == rusclass)

    def __str__(self):
        try:
            p = self.profile
        except:
            p = None
        return '%s (%s)' % (p, self.year)

    class Meta:
        ordering = ['-year']
        verbose_name = 'tutor'
        verbose_name_plural = verbose_name + 'er'
        unique_together = (('profile', 'year'),)


class TutorInTutorGroup(models.Model):
    tutorgroup = models.ForeignKey(TutorGroup, to_field='id')
    tutor = models.ForeignKey(Tutor)


@python_2_unicode_compatible
class BoardMember(models.Model):
    id = models.AutoField(primary_key=True)
    tutor = models.ForeignKey(Tutor)
    position = models.IntegerField(verbose_name="Rækkefølge")
    title = models.CharField(max_length=50, verbose_name="Titel")

    def __str__(self):
        return "%s %s" % (self.title, self.tutor)

    class Meta:
        ordering = ['tutor__year', 'position']
        verbose_name = 'bestyrelsesmedlem'
        verbose_name_plural = verbose_name + 'mer'


# Freshman semester of a user for a single year
class Rus(models.Model):
    objects = RusManager()

    id = models.AutoField(primary_key=True)
    profile = models.ForeignKey(TutorProfile)
    year = models.IntegerField(verbose_name="Tutorår")
    rusclass = models.ForeignKey(RusClass, null=True)

    arrived = models.BooleanField(verbose_name="Ankommet", default=False)
    initial_rusclass = models.ForeignKey(
        RusClass, null=True, related_name='initial_rus_set')

    class Meta:
        verbose_name = 'rus'
        verbose_name_plural = verbose_name + 'ser'

        ordering = ['rusclass', 'profile']

    def json_of(self):
        if self.initial_rusclass:
            initial_handle = self.initial_rusclass.handle
        else:
            initial_handle = None
        return {
            'year': self.year,
            'rusclass': self.rusclass.handle,
            'arrived': self.arrived,
            'pk': self.profile.pk,

mftutor/browser/views.py
# vim: set fileencoding=utf8:
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, get_list_or_404
from django import forms
from django.db.models import Count

from ..tutor.models import TutorProfile, RusClass, TutorGroup, Tutor

class ProfileView(TemplateView):
    template_name = 'browser/profile.html'

    def get_context_data(self, **kwargs):
        context_data = super(ProfileView, self).get_context_data(**kwargs)
        tp = get_object_or_404(TutorProfile, studentnumber=self.kwargs['studentnumber'])
        context_data['subject'] = tp
        years = []
        for tutor in tp.tutor_set.all().select_related('profile__tutor'):
            years.append({'year': tutor.year, 'tutor': tutor})
        for rus in tp.rus_set.all().select_related('profile__tutor'):
            years.append({'year': rus.year, 'rus': rus})
        context_data['years'] = sorted(years, key=lambda y: y['year'])
        return context_data

class RusClassView(TemplateView):
    template_name = 'browser/rusclass.html'

    def get_context_data(self, **kwargs):
        context_data = super(RusClassView, self).get_context_data(**kwargs)
        context_data['rusclass'] = get_object_or_404(RusClass, year=self.kwargs['year'], handle=self.kwargs['handle'])
        return context_data

class GroupView(TemplateView):
    template_name = 'browser/group.html'

    def get_context_data(self, **kwargs):
        context_data = super(GroupView, self).get_context_data(**kwargs)
        context_data['year'] = self.kwargs['year']
        group = context_data['group'] = get_object_or_404(TutorGroup, handle=self.kwargs['handle'])
        context_data['members'] = get_list_or_404(Tutor, year=self.kwargs['year'], groups=group)
        return context_data

class SearchForm(forms.Form):
    query = forms.CharField()
    tutors_only = forms.BooleanField(required=False, initial=True)

class SearchView(TemplateView):
    template_name = 'browser/search.html'

    def get_context_data(self, **kwargs):
        context_data = super(SearchView, self).get_context_data(**kwargs)
        form = SearchForm(self.request.GET)
        if form.is_valid():
            query = context_data['query'] = form.cleaned_data['query']
            if form.cleaned_data['tutors_only']:
                context_data['results'] = (
                        TutorProfile.objects.filter(name__icontains=query)
                        .annotate(tutor_count=Count('tutor'))
                        .filter(tutor_count__gt=0))
            else:
                context_data['results'] = TutorProfile.objects.filter(name__icontains=query)[0:30]
        else:
            form = SearchForm()
        context_data['form'] = form
        return context_data

mftutor/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- vim:set sw=2 sts=2 et: -->
<!--
Mat/Fys-Tutorgruppens hjemmeside er designet af Mathias Løkke Madsen i 2012.
Hjemmesiden er implementeret af webgruppen 2013, ledet af webansvarlige Mathias Rav.
Kildekoden er frit tilgængelig: https://github.com/matfystutor/web/
-->
<html>
<head>
  <meta charset="utf-8" />
  <link rel="stylesheet" href="{% static "stylesheet.css" %}" type="text/css" media="screen, projection" />
  <link rel="stylesheet" href="{% static "style_print.css" %}" type="text/css" media="print" />
  <title>{% block fulltitle %}{% block title %}Forside{% endblock %} - Mat/Fys-Tutorgruppen{% endblock %}</title>
  <meta name="description" content="" />
  <meta name="viewport" content="width=750px" />
  <script type="text/javascript" src="{% static "css_browser_selector.js" %}"></script>
  <script type="text/javascript" src="{% static "script.js" %}"></script>
  {% block head %}{% endblock %}
</head>
<body class="{{ BODY_CLASS }} {% block bodyclass %}{% endblock %}">
<div id="background">
<div id="main">
  {% block header %}
  <div id="header" style="position: relative"><a href="/"><img src="{% static "images/header.jpg" %}" /></a>
  </div>
  {% endblock %}
<div id="menu">
  <div id="menu-list">
    <ul class="topnav">
      {% block menu %}
      <li class="trigger">
      <a href="{% url 'news' %}">Info</a>
      <ul class="subnav">
        <li><a href="{% url 'intro' %}">Introduktion</a></li>
        <li><a href="{% url 'news' %}">Nyheder</a></li>
        <li><a href="{% url 'board' %}">Bestyrelsen</a></li>
        <li><a href="{% url 'vedtaegter' %}">Vedtægter</a></li>
        <li><a href="{% url 'events' %}">Kalender</a></li>
        <li><a href="{% url 'gruppekatalog' %}">Gruppekatalog</a></li>
        <li><a href="{% url 'rus2tur' %}">Rus2Tur</a></li>
        <li><a href="{% url 'sponsor' %}">Sponsor</a></li>
        <li><a href="{% url 'kontakt' %}">Kontakt</a></li>
      </ul>
      </li>
      {% if tutor %}
      <li class="trigger">
      <a href="{% url 'tutors' %}">Tutorer</a>
      <ul class="subnav">
        <li><a href="{% url 'gallery' %}">Billeder</a></li>
        <li><a href="{% url 'tutors' %}">Adresser</a></li>
        <li><a href="{% url 'aliases' %}">Mailalias</a></li>
        <li><a href="{% url 'list_guides' %}">Guides</a></li>
        <li><a href="{% url 'list_udgivelser' %}">Udgivelser</a></li>
        <li><a href="{% url 'list_referater' %}">Referater</a></li>
        <li><a href="{% url 'feeds' %}">Feeds</a></li>
      </ul>
      </li>
      <li class="trigger">
      <a href="#" style="cursor: default" onclick="return false">Personligt</a>
      <ul class="subnav">
        <li><a href="{% url 'profile_view' %}">Profil</a></li>
        <li><a href="{% url 'groups_view' %}">Mine Grupper</a></li>
        <li><a href="{% url 'password_change' %}">Ændre kodeord</a></li>
        <li><a href="{% url 'events' %}">Tilmeldinger</a></li>
        <li><a href="{% url 'upload_picture_view' %}">Upload Billede</a></li>
        <!--<li><a href="{% url 'shirt_preference' %}">T-shirt-størrelse</a></li>-->
        <!--<li><a href="{% url 'own_confirmation' %}">Tutorbekræftelse</a></li>-->
      </ul>
      </li>
      {% else %}
      <li class="trigger">
      <a href="{% url 'kontakt' %}">Kontakt</a>
      </li>
      {% endif %}
      {% if tutor.is_tutorbur %}
      <li class="trigger">
      <a href="{% url 'bur_start' %}">{{ BURET }}</a>
      <ul class="subnav">
        <li><a href="{% url 'rusinfo_list' %}">Russer</a></li>
        <li><a href="{% url 'burtavle_admin' %}">Burtavle</a></li>
        <li><a href="{% url 'handout_list' %}">Tilmeldinger</a></li>
        <li><a href="{% url 'reg_rus_list' %}">Registrering</a></li>
        <li><a href="{% url 'reg_changes' %}">Ændrede russer</a></li>
        <li><a href="{% url 'import_session_choose' %}">Importer russer</a></li>
      </ul>
      </li>
      {% elif tutor.has_rusclass %}
      <li class="trigger">
      <a href="{% url 'rusinfo_list' %}">Russer</a>
      <ul class="subnav">
      </ul>
      </li>
      {% endif %}
      {% if tutor.is_tutorbest %}
      <li class="trigger">
      <a href="{% url 'admin:index' %}">Administration</a>
      <ul class="subnav">
        <li><a href="{% url 'tutor_admin' %}">Tutorer</a></li>
        <li><a href="{% url 'admin:aliases_alias_changelist' %}">Aliaser</a></li>
        <li><a href="{% url 'admin:news_newspost_changelist' %}">Forsidenyheder</a></li>
        <li><a href="{% url 'admin:events_event_changelist' %}">Kalender</a></li>
        <li><a href="{% url 'confirmation_table' %}">Tutorbekræftelser</a></li>
        <li><a href="{% url 'confirmation_card' %}">Tutorkort</a></li>
      </ul>
      </li>
      {% endif %}
      {% endblock %}
    </ul>
  </div>
  <div class="loginout">
    {% if user.is_authenticated %}
    <form id="logout" method="post" action="{% url 'logout_view' %}">{% csrf_token %}
    <input type="hidden" name="next" value="{{ request_path }}" />
    {{ profile.get_full_name }}&nbsp;&nbsp;
      <input type="submit" class="link_button" value="Log ud" />
    </form>
    {% else %}
    <form id="login" method="post" action="{% url 'tutor_login' %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ request_path }}" />
      <fieldset>
        <input name="username" type="text" id="user-login" placeholder="Årskortnr" />
        <input name="password" type="password" id="password-login" placeholder="Password" />
        <input name="login" type="submit" class="submit-button" value="LOGIN" />
      </fieldset>
    </form>
    {% endif %}
  </div>
</div>
<div id="content">
  {% block content %}{% endblock %}
<div class="clear"></div>
</div>
{% block bottom %}
{% endblock %}
</div>
</div>
</body>
</html>

mftutor/templates/tutors.html
{% extends "base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% block title %}Adresseliste{% endblock %}
{% block head %}
<script type="text/javascript" src="{% static "navneleg.js" %}"></script>
{% endblock %}
{% block bodyclass %}tutors{% endblock %}
{% block content %}
<p>
Vælg gruppe:
<select onchange="location = this.value">
<option value="{% url 'tutors' %}">----</option>
{% for g in groups %}
<option value="{% url 'tutorgroup' g.handle %}"{% if group == g.handle %} selected="selected"{% endif %}>{{ g.name }}</option>
{% endfor %}
</select>
</p>
{% if group %}
<p><a href="{% url "tutordumpgroup" group=group %}">Eksporter gruppen til Google Contacts</a></p>
{% else %}
<p><a href="{% url "tutordump" %}">Eksporter alle tutorer til Google Contacts</a></p>
{% endif %}
<p>Vis som:
<label>
<input onclick="document.getElementsByClassName('tutorcontainer')[0].className = 'tutorcontainer tutorlist'"
name="tutorcontainer" type="radio" value="tutorlist" checked="checked"> Liste</label>
<label>
<input onclick="document.getElementsByClassName('tutorcontainer')[0].className = 'tutorcontainer tutortable'"
name="tutorcontainer" type="radio" value="tutortable"> Tabel</label>
</p>
<p>
Antal tutorer: {{ tutor_count }}
</p>
<p>
Gruppeansvarlig:
</p>
<div class="tutorcontainer tutorlist">
{% for tutor in tutor_list %}
<div class="tutoraddress tutor{{ tutor.studentnumber }}">
 <div class="pic">
  {% if tutor.picture %}
  <a target="_blank" href="{{ tutor.picture }}">
{% thumbnail tutor.picture "130x130" crop="center" as im %}
<img class="tutorpicture" src="{{ im.url }}" /></a>
{% endthumbnail %}
{% endif %}
 </div> <!-- /pic -->
 <div class="detailscontainer">
  <div class="detailsmagic"></div><div class="details">
   <div class="name">
    {{ tutor.full_name }}
   </div> <!-- /name -->
   <ul>
    <li title="Adresse" class="street">{{ tutor.street }}</li>
    <li title="By" class="city">{{ tutor.city }}</li>
    <li title="Telefon" class="phone">
    <a href="tel:{{ tutor.phone }}">{{ tutor.phone }}</a></li>
    <li title="Email" class="email"><a href="mailto:{{ tutor.email }}">{{ tutor.email }}</a></li>
    <li title="Studium" class="study">{{ tutor.study }}</li>
    <li title="Årskort" class="studentnumber">{{ tutor.studentnumber }}</li>
   </ul>
  </div> <!-- /details -->
  <div class="detailsoverflow"></div>
 </div> <!-- /detailscontainer -->
</div> <!-- /tutoraddress -->

{% endfor %}
</div>
{% endblock %}